name: linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ghcr.io/abcfy2/musl-cross-toolchain-ubuntu:${{ matrix.cross_host }}"
    strategy:
      fail-fast: false
      matrix:
        cross_host:
          # - arm-unknown-linux-musleabi
          - aarch64-unknown-linux-musl
          # - loongarch64-unknown-linux-musl
          # - mips-unknown-linux-musl
          # - mipsel-unknown-linux-musl
          # - mips64-unknown-linux-musl
          - x86_64-unknown-linux-musl
          # - i686-unknown-linux-musl
        # use_libressl: [0, 1]
    steps:
    - uses: actions/checkout@v4
    - name: Build aria2
      env:
        CROSS_HOST: "${{ matrix.cross_host }}"
        USE_LIBRESSL: "${{ matrix.use_libressl }}"
      run: |
        chmod +x ./linux-build.sh
        ./linux-build.sh
        ls -lah
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: aria_${{ matrix.os }}
        path: aria2c