name: linux

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Linux setup
      run: |
        sudo apt-get update
        sudo apt-get install \
          binutils \
          g++-12 \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config \
          libssl-dev \
          libc-ares-dev \
          libxml2-dev \
          zlib1g-dev \
          libsqlite3-dev \
          libssh2-1-dev \
          libcppunit-dev
    - name: Setup gcc (Linux)
      run: |
        echo 'CC=gcc-12' >> $GITHUB_ENV
        echo 'CXX=g++-12' >> $GITHUB_ENV
    - name: Libtool
      run: |
        autoreconf -i
    - name: Setup compiler flags
      run: |
        asanflags="-fsanitize=address,undefined -fno-sanitize-recover=undefined"

        CPPFLAGS="$asanflags -O2"
        LDFLAGS="$asanflags"

        echo 'CPPFLAGS='"$CPPFLAGS" >> $GITHUB_ENV
        echo 'LDFLAGS='"$LDFLAGS" >> $GITHUB_ENV
    - name: Configure autotools (Linux, openssl)
      run: |
        ./configure \
          --enable-static \
          --disable-shared \
          --enable-metalink \
          --enable-bittorrent \
          --disable-nls \
          --with-libgmp \
          --with-sqlite3 \
          --with-libz \
          --with-libexpat \
          --with-libcares \
          --with-libgcrypt \
          --with-libssh2 \
          --without-libuv \
          --without-gnutls \
          --without-openssl \
          --without-libnettle \
          --without-libxml2 \
          ARIA2_STATIC=yes
    - name: Build aria2
      run: |
        make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)" check
        ls -lah src
        ls -lah
        strip src/aria2c
        ldd src/aria2c
        file src/aria2c
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: aria_${{ matrix.os }}
        path: src/aria2c