name: macos

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build aria2
      run: |
        mkdir build-release && cd build-release
        ln -s ../makerelease-osx.mk Makefile
        export NON_RELEASE=1
        make aria2.build
        ls -lah
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: aria_${{ matrix.os }}
        path: src/aria2c