name: macos

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: MacOS setup
      run: |
        brew update
        brew install m4 autoconf automake pkg-config libtool gettext cppunit
        brew reinstall --build-from-source \
          openssl libssh2 c-ares sqlite3 gmp expat libgcrypt
    - name: Setup clang (MacOS)
      run: |
        echo 'CC=clang' >> $GITHUB_ENV
        echo 'CXX=clang++' >> $GITHUB_ENV
    - name: Libtool
      run: |
        autoreconf -i
    - name: Setup compiler flags
      run: |
        asanflags="-fsanitize=address,undefined -fno-sanitize-recover=undefined"

        CPPFLAGS="$asanflags -o2"
        LDFLAGS="$asanflags"

        echo 'CPPFLAGS='"$CPPFLAGS" >> $GITHUB_ENV
        echo 'LDFLAGS='"$LDFLAGS" >> $GITHUB_ENV
    - name: Configure autotools (macOS)
      run: |
        ./configure \
          --enable-static \
          --disable-shared \
          --enable-metalink \
          --enable-bittorrent \
          --disable-nls \
          --with-appletls \
          --with-libgmp \
          --with-sqlite3 \
          --with-libz \
          --with-libexpat \
          --with-libcares \
          --with-libgcrypt \
          --with-libssh2 \
          --without-libuv \
          --without-gnutls \
          --without-openssl \
          --without-libnettle \
          --without-libxml2 \
          ARIA2_STATIC=yes \
          LIBS="-lgmp -lsqlite3 -lz -lexpat -lcares -lgcrypt -lssh2"
    - name: Build aria2
      run: |
        make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)" check
        strip -x src/aria2c
        otool -L src/aria2c
        file src/aria2c
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: aria_${{ matrix.os }}
        path: src/aria2c