name: mingw

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile.mingw
        context: .
        outputs: type=local,dest=./output
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ./output/aria2/src/aria2c.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}